### PR TITLE
Bump resolvers

### PR DESCRIPTION
**Pull request by alanz**
cabal to 2020-05-02T10:11:15Z
stack-8.8.3 to lts-15.10
stack to nightly-2020-05-01

### CODE REVIEW

**Comment by alanz** [comment]
@jneira please give an opinion as to what test failures can be ignored.

**Comment by jneira** [comment]
jumm i think we have to take care of this one:

```
src/Haskell/Ide/Engine/Plugin/Ormolu.hs:73:46: error:
    • Couldn't match type ‘Bool’ with ‘RegionIndices’
      Expected type: Config RegionIndices
        Actual type: Config Bool
    • In the first argument of ‘ormolu’, namely ‘(conf o)’
      In the expression: ormolu (conf o) fp
      In the second argument of ‘try’, namely
        ‘(ormolu (conf o) fp $ T.unpack cont)’
   |
73 |       liftIO $ try @OrmoluException (ormolu (conf o) fp $ T.unpack cont)
   |                                              ^^^^^^
cabal: Failed to build haskell-ide-engine-1.3 (which is required by
exe:hie-wrapper from haskell-ide-engine-1.3, lib:hie-test-utils from
haskell-ide-engine-1.3 and others).
```
It is thrown for cabal jobs with ghc-8.8.3 and ghc-8.8.2

**Comment by alanz** [comment]
Weird that it builds fine with 8.8.3 and ormolu-0.0.3.1for stack. Investigating, can repeat it with my machine.

**Comment by fendor** [comment]
We have to limit the acceptable ormolu version
New release 0.5.0.0 is incompatible with HIE.

**Comment by alanz** [comment]
Green on circleCI. Ok to merge?
