### ISSUE TITLE
haddock error

### ISSUE THREAD

**Issue by stevenyvr987** [haskell/haskell-ide-engine#426]
I'm getting a haddock error
```
$ haddock hie-build-plugin/Haskell/Ide/BuildPlugin.hs
Haddock coverage:

hie-build-plugin/Haskell/Ide/BuildPlugin.hs:308:9: error:
    parse error on input ‘-- * Backwards incompatible change to '
```
It looks like the comment line `-- *` in file hie-build-plugin/Haskell/Ide/BuildPlugin.hs is being interpreted as a section header by haddock, but section headers can't seem to be defined inside code, only at the top-level or within a `module` statement.

Here is a simplified example in a file called x.hs:
```
-- * ok
main = do
  -- * not ok
  let x = 1
  return ()
````
If I process x.hs by haddock, I don't get an error on the first comment line, but do get an error on the second:
```
haddock x.hs
Haddock coverage:

x.hs:3:3: error: parse error on input ‘-- * not ok’
```
I did a grep for similar patterns in all haskell files (`ag --haskell '\-\- \*' .`) but couldn't find any other bad instances of `-- *`.

**Comment by nponeccop** [comment]
Interestingly we merged https://github.com/haskell/haskell-ide-engine/pull/424/files some time ago

**Comment by domenkozar** [comment]
cc @shlevy

**Comment by shlevy** [comment]
@nponeccop This issue was a little over 12 hours after the merge, so probably @stevenyvr987 hadn't pulled yet? Certainly the error message doesn't contain the extra spaces my PR added.

**Comment by stevenyvr987** [comment]
Yes, I had not pulled one more time before reporting the issue. After pulling, I tried `stack haddock` on the project, and although I still can't do it successfully, at least the error reported in this issue is gone. I'll close the issue now.

There still seems to be a problem with `stack haddock`. I am using most recent version of stack and lts-10.0 of stackage. I'll try to figure out the error message and report a new issue if needed.
